### ISSUE TITLE
editor should support glTF

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three.js#2]
requires adding a bunch of filetypes but would be lovely

**Comment by takahirox** [comment]
You mean, Three.js editor, correct?
IIRC, it doesn't support skin model yet.

Loading non-skin model won't be so hard but
to handle skin-model we first need to solve 
SkinnedMesh/Skeleton` serialization/deserializatoin
which is tightly related to shared Skeleton.

**Comment by donmccurdy** [comment]
Yeah. I'm not concerned yet about [de]serializing meshes (custom glTF shaders will be another blocker there), so much as just having a quick drag-and-drop way to preview glTF files.

**Comment by takahirox** [comment]
Cool, that's reasonable.

IIRC, editor's history and auto-save features require [de]serialization
so you maybe need to turn them off for skin models.

Just FYI: I've tried Skin model editor on Three.js before
SkinnedMesh support on Editor PR(not merged): https://github.com/mrdoob/three.js/pull/8422
MMD Editor on Three.js: https://twitter.com/superhoge/status/795930984382271489

**Comment by donmccurdy** [comment]
Progress! https://gltf-viewer.donmccurdy.com/

![38c25b4d-9c8b-404c-a9c9-d861b9cc3ba8-89424-0000f56c772e1ebd](https://cloud.githubusercontent.com/assets/1848368/25062193/5d53dade-217c-11e7-8680-2d09ff8f92e8.gif)

(... just not on the serialization part 😑 )

**Comment by takahirox** [comment]
Coooooool!!

**Comment by donmccurdy** [comment]
three.js editor supports glTF1 already, presumably glTF2 when we deprecate glTF1. Closing this bug for now.
