### ISSUE TITLE
I'd like to update feat-gltf-draco-extension-v4 to latest improvements in dev

### ISSUE THREAD

**Issue by zynga-jpetersen** [donmccurdy/three.js#5]
Greetings,

Your integration of draco into GLTFLoader is very clean in this branch, so I'd like to bring it up to date with latest dev (getting the geometry optimizations particularly).
 
If there is another version of the GLTFLoader with draco support that I should be looking at, or a different branch I should be updating, please point me to that one instead (and I'll gladly update and switch to using that one).

Thanks again and great work.

**Comment by zynga-jpetersen** [comment]
I'm still up for doing an integration, but back porting just the geometry cache doesnt seem to pay off with my model + draco. I think that's because I added mesh deduplication to the sketchfab unity exporter (which I'm going to be giving back), so I dont seem to fall into the isPrimitiveEqual being true ever.

**Comment by donmccurdy** [comment]
@zynga-jpetersen I've rebased the branch against three.js dev, although there's still a TODO for getting the geometry cache to handle Draco meshes. The updated code works with the sample model on the branch, but I haven't tested beyond that.

**Comment by zynga-jpetersen** [comment]
Thanks I'll try it out today.

**Comment by donmccurdy** [comment]
Oh, also note that we've (just) merged some changes to THREE.DRACOLoader: https://github.com/mrdoob/three.js/pull/12895

That may affect this branch as well, I haven't had the chance to rebase again since then.
